# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf589b0cb72e77a4cef185de08ef11e0a1146541e0dfc34cb8037452add533726d69209ce40aaa76fee033f43adba4db098d691d2ba99051e79245bb8034443d

test:
  secret_key_base: 66d15c45c128f7a0bc9f6a456dabfd7822ae73c02010dc5bfaae98a8100682720edde172aa8997991315712e918b0994fdfd2d7aad194ef5e399041b6bb6f31c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
